;; (setq selected-theme 'modus-vivendi)
(setq selected-theme 'base16-monokai)
;; (setq selected-theme 'doom-one-light)
(load-theme selected-theme)
(enable-theme selected-theme)

;; (load-theme 'base16-monokai t)
;; (enable-theme 'base16-monokai)
;; (load-theme 'doom-one-light)
;; (enable-theme 'doom-one-light)
(provide 'init-theme)
